# Generated by Django 6.0.5 on 2026-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('studens', 'Student'), ('teacher', 'Teacher')], default='student', max_length=50),
        ),
    ]
